{
	"openapi": "3.1.0",
	"info": {
		"title": "Bucket List API",
		"version": "0.1.0"
	},
	"paths": {
		"/": {
			"get": {
				"summary": "Get Coasters and Bucket List Counts",
				"description": "Get all coasters and the amount of bucket lists they are in",
				"responses": {
					"200": {
						"description": "List of Coasters and Bucket List Counts",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/CoasterAndBucketListCount"
									}
								},
								"example": [
									{
										"coaster": {
											"id": 2832,
											"name": "Zadra",
											"speed": 121,
											"height": 63,
											"length": 1316,
											"inversions": 3,
											"manufacturer": {
												"name": "Rocky Mountain Construction"
											},
											"park": {
												"id": 545,
												"name": "Energylandia",
												"country": "Poland"
											},
											"image": "https://pictures.captaincoaster.com/1440x1440/9f68e5f6-f989-4f0d-a9f8-1330dad339e3.jpg"
										},
										"bucket_list_count": 12
									},
									{
										"coaster": {
											"id": 2827,
											"name": "Taiga",
											"speed": 106,
											"height": 52,
											"length": 1104,
											"inversions": 4,
											"manufacturer": {
												"name": "Intamin"
											},
											"park": {
												"id": 117,
												"name": "Linnanmäki",
												"country": "Finland"
											},
											"image": "https://pictures.captaincoaster.com/1440x1440/9a6ed72f-34c7-4353-bcf5-49fbae03718b.jpeg"
										},
										"bucket_list_count": 8
									}
								]
							}
						}
					},
					"404": {
						"description": "Bucket List not found"
					}
				}
			}
		},
		"/{user_id}": {
			"get": {
				"summary": "Get Coasters in a Bucket List",
				"description": "Get all coasters in a bucket list",
				"responses": {
					"200": {
						"description": "List of Coasters in Bucket List",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Coaster"
									}
								},
								"example": [
									{
										"id": 2832,
										"name": "Zadra",
										"speed": 121,
										"height": 63,
										"length": 1316,
										"inversions": 3,
										"manufacturer": {
											"name": "Rocky Mountain Construction"
										},
										"park": {
											"id": 545,
											"name": "Energylandia",
											"country": "Poland"
										},
										"image": "https://pictures.captaincoaster.com/1440x1440/9f68e5f6-f989-4f0d-a9f8-1330dad339e3.jpg"
									},
									{
										"id": 2827,
										"name": "Taiga",
										"speed": 106,
										"height": 52,
										"length": 1104,
										"inversions": 4,
										"manufacturer": {
											"name": "Intamin"
										},
										"park": {
											"id": 117,
											"name": "Linnanmäki",
											"country": "Finland"
										},
										"image": "https://pictures.captaincoaster.com/1440x1440/9a6ed72f-34c7-4353-bcf5-49fbae03718b.jpeg"
									}
								]
							}
						}
					},
					"404": {
						"description": "Bucket List not found"
					}
				}
			},
			"put": {
				"summary": "Set Coasters in a Bucket List",
				"description": "Set all coasters in a bucket list",
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "array",
								"items": {
									"type": "integer",
									"format": "uint32",
									"minimum": 0.0
								}
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "Set Bucket List"
					},
					"401": {
						"description": "Unauthorized"
					},
					"404": {
						"description": "Bucket List not found"
					}
				},
				"security": [
					{
						"jwt": []
					}
				]
			},
			"post": {
				"summary": "Add a Coaster",
				"description": "Add a coaster to a bucket list",
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "integer",
								"format": "uint32",
								"minimum": 0.0
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "Added to Bucket List"
					},
					"401": {
						"description": "Unauthorized"
					},
					"404": {
						"description": "Bucket List not found"
					}
				},
				"security": [
					{
						"jwt": []
					}
				]
			}
		},
		"/{user_id}/{index}": {
			"get": {
				"summary": "Get a Coaster by index",
				"description": "Get a coaster at a given index in a bucket list",
				"responses": {
					"200": {
						"description": "Coaster in Bucket List",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Coaster"
								},
								"example": {
									"id": 2827,
									"name": "Taiga",
									"speed": 106,
									"height": 52,
									"length": 1104,
									"inversions": 4,
									"manufacturer": {
										"name": "Intamin"
									},
									"park": {
										"id": 117,
										"name": "Linnanmäki",
										"country": "Finland"
									},
									"image": "https://pictures.captaincoaster.com/1440x1440/9a6ed72f-34c7-4353-bcf5-49fbae03718b.jpeg"
								}
							}
						}
					},
					"404": {
						"description": "Bucket List not found or index out of bounds"
					}
				}
			},
			"post": {
				"summary": "Insert a Coaster by index",
				"description": "Insert a coaster at a given index into a bucket list",
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "integer",
								"format": "uint32",
								"minimum": 0.0
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "Inserted into Bucket List"
					},
					"401": {
						"description": "Unauthorized"
					},
					"404": {
						"description": "Bucket List not found"
					}
				},
				"security": [
					{
						"jwt": []
					}
				]
			},
			"delete": {
				"summary": "Delete a Coaster by index",
				"description": "Delete a coaster at a given index from a bucket list",
				"responses": {
					"200": {
						"description": "Deleted from Bucket List"
					},
					"401": {
						"description": "Unauthorized"
					},
					"404": {
						"description": "Bucket List not found or index out of bounds"
					}
				},
				"security": [
					{
						"jwt": []
					}
				]
			}
		}
	},
	"components": {
		"securitySchemes": {
			"jwt": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		},
		"schemas": {
			"Coaster": {
				"type": "object",
				"required": [
					"id",
					"name"
				],
				"properties": {
					"height": {
						"type": [
							"integer",
							"null"
						],
						"format": "uint32",
						"minimum": 0.0
					},
					"id": {
						"type": "integer",
						"format": "uint32",
						"minimum": 0.0
					},
					"image": {
						"type": [
							"string",
							"null"
						]
					},
					"inversions": {
						"type": [
							"integer",
							"null"
						],
						"format": "uint32",
						"minimum": 0.0
					},
					"length": {
						"type": [
							"integer",
							"null"
						],
						"format": "uint32",
						"minimum": 0.0
					},
					"manufacturer": {
						"anyOf": [
							{
								"$ref": "#/components/schemas/Manufacturer"
							},
							{
								"type": "null"
							}
						]
					},
					"name": {
						"type": "string"
					},
					"park": {
						"anyOf": [
							{
								"$ref": "#/components/schemas/Park"
							},
							{
								"type": "null"
							}
						]
					},
					"speed": {
						"type": [
							"integer",
							"null"
						],
						"format": "uint32",
						"minimum": 0.0
					}
				}
			},
			"CoasterAndBucketListCount": {
				"type": "object",
				"required": [
					"bucket_list_count",
					"coaster"
				],
				"properties": {
					"bucket_list_count": {
						"type": "integer",
						"format": "uint32",
						"minimum": 0.0
					},
					"coaster": {
						"$ref": "#/components/schemas/Coaster"
					}
				}
			},
			"Country": {
				"type": "string",
				"enum": [
					"Argentina",
					"Australia",
					"Austria",
					"Belgium",
					"Brazil",
					"Burma",
					"Canada",
					"China",
					"Colombia",
					"Cyprus",
					"CzechRepublic",
					"Denmark",
					"Finland",
					"France",
					"Germany",
					"Guatemala",
					"Hungary",
					"India",
					"Indonesia",
					"Iraq",
					"Ireland",
					"Israel",
					"Italy",
					"Japan",
					"Lebanon",
					"Malaysia",
					"Mexico",
					"Mongolia",
					"Netherlands",
					"NewZealand",
					"Norway",
					"Peru",
					"Poland",
					"Portugal",
					"Qatar",
					"Russia",
					"Singapore",
					"SouthAfrica",
					"SouthKorea",
					"Spain",
					"Sweden",
					"Switzerland",
					"Taiwan",
					"Thailand",
					"Turkey",
					"Ukraine",
					"UnitedArabEmirates",
					"UnitedKingdom",
					"UnitedStates",
					"Vietnam"
				]
			},
			"Manufacturer": {
				"type": "object",
				"required": [
					"name"
				],
				"properties": {
					"name": {
						"type": "string"
					}
				}
			},
			"Park": {
				"type": "object",
				"required": [
					"id",
					"name"
				],
				"properties": {
					"country": {
						"anyOf": [
							{
								"$ref": "#/components/schemas/Country"
							},
							{
								"type": "null"
							}
						]
					},
					"id": {
						"type": "integer",
						"format": "uint32",
						"minimum": 0.0
					},
					"name": {
						"type": "string"
					}
				}
			}
		}
	}
}
